# Install dependencies
using Pkg
Pkg.add("PyCall")
#Pkg.build("PyCall")
Pkg.add("SparseArrays")
Pkg.add("LinearAlgebra")
Pkg.add("Pardiso")
Pkg.add("IterativeSolvers")
Pkg.add("WriteVTK")
Pkg.add("Printf")
Pkg.add("Statistics")
Pkg.add("Random")
Pkg.add("NearestNeighbors")
Pkg.add("DataFrames")
Pkg.add("Printf")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("PyPlot")
Pkg.add("Interpolations")
Pkg.add("SpecialFunctions")
Pkg.add("AlgebraicMultigrid")
Pkg.add("ProfileSVG")
Pkg.add("HDF5")