# Install dependencies
add("Pkg")
add("SparseArrays")
add("LinearAlgebra")
add("Pardiso")
add("IterativeSolvers")
add("WriteVTK")
add("Printf")
add("Statistics")
add("Random")
add("NearestNeighbors")
add("DataFrames")
add("Printf")
add("CSV,DataFrames")
add("PyPlot")
add("Interpolations")