########## Model Plots ##########
function get_plots(grid::CartesianGrid,S::Matrix{Float64},T::Matrix{Float64},X::Matrix{Float64},time_type::String,plot_dir::String)
    if time_type == "initial"
        figure()
        title(L"Initial\,Melt\,Fraction")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,X)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        gca().set_aspect("equal")
    	savefig(plot_dir*"/initial_melt_fraction.png")
        close()
        
        figure()
        title(L"Initial\,Temperature")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,T)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        gca().set_aspect("equal")
    	savefig(plot_dir*"/initial_temperature.png")
        close()
        
        figure()
        title(L"Initial\,Entropy")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,S)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        gca().set_aspect("equal")
    	savefig(plot_dir*"/initial_entropy.png")
        close()

    elseif time_type == "final"
        figure()
        title(L"Final\,Melt\,Fraction")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,X)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        gca().set_aspect("equal")
	savefig(plot_dir*"/final_melt_fraction.png")
        close() 
        
        figure()
        title(L"Final\,Temperature")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,T)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        gca().set_aspect("equal")
    	savefig(plot_dir*"/final_temperature.png")
        close() 
        
        figure()
        title(L"Final\,Entropy")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,S)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        gca().set_aspect("equal")
    	savefig(plot_dir*"/final_entropy.png")
        close()
    end
end

function get_plots_new(grid::CartesianGrid,S::Matrix{Float64},T::Matrix{Float64},X::Matrix{Float64},time_type::String,plot_dir::String)
    if time_type == "initial"
        figure(figsize=(16, 4))
        subplot(1,3,1)
        title(L"Initial\,Melt\,Fraction")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,X)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        # gca().set_aspect("equal")
        tight_layout()
        subplot(1,3,2)
        title(L"Initial\,Temperature")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,T)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        # gca().set_aspect("equal")
        tight_layout()
        subplot(1,3,3)
        title(L"Initial\,Entropy")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,S)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        # gca().set_aspect("equal")
        tight_layout()
        savefig(plot_dir*"/initial_plots.png",dpi=300)
        close()
    elseif time_type == "final"
        figure(figsize=(16, 4))
        subplot(1,3,1)
        title(L"Final\,Melt\,Fraction")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,X)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        # gca().set_aspect("equal")
        tight_layout()
        subplot(1,3,2)
        title(L"Final\,Temperature")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,T)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        # gca().set_aspect("equal")
        tight_layout()
        subplot(1,3,3)
        title(L"Final\,Entropy")
        cs = contour(grid.xc/1e3,grid.yc/1e3,X,[0.5],colors="red")
        clabel(cs,inline=true,fontsize=8,fmt="ocean-ice interface")
        pcolor(grid.xc/1e3,grid.yc/1e3,S)
        colorbar(cmap="viridis")
        gca().set_ylabel(L"Height\,(km)")
        gca().set_xlabel(L"Width\,(km)")
        gca().invert_yaxis()
        # gca().set_aspect("equal")
        tight_layout()
        savefig(plot_dir*"/final_plots.png",dpi=300)
        close()
    end
end

function thickness_over_time(grid::CartesianGrid,thickness_array::Vector{Any},time_plot::Vector{Any},itime::Int64)
    figure()
    for i in 1:ceil(Int,itime/10):itime-1
        plot(grid.xc/1e3,thickness_array[i]/1e3,label=(L"At",@sprintf("%.3g",time_plot[i]/3.15e7/1e6),L"Myr"))
    end
    title(L"Profile\,of\,Ocean-Ice\,Inferface\,Topograpgy\,Over\,Time")
    gca().invert_yaxis()
    # Legend is at the bottom
    legend(loc="upper center",bbox_to_anchor=(0.5,-0.15),ncol=5)
    show()
end